# Generated by Django 5.2.4 on 2025-12-05 15:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id_tipo_alergia', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Alergia',
                'verbose_name_plural': 'Tipos de Alergia',
                'db_table': 'alergia',
            },
        ),
        migrations.CreateModel(
            name='ano_electivo',
            fields=[
                ('id_año_electivo', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ano_electivo',
            },
        ),
        migrations.CreateModel(
            name='Area_conocimiento',
            fields=[
                ('id_area_conocimiento', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'area_conocimiento',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id_tipo_discapacidad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Discapacidad',
                'verbose_name_plural': 'Tipos de Discapacidad',
                'db_table': 'discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Sisben',
            fields=[
                ('id_tipo_sisben', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Sisben',
                'verbose_name_plural': 'Tipos Sisben',
                'db_table': 'sisben',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id_tipo_actividad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'db_table': 'tipo_actividad',
            },
        ),
        migrations.CreateModel(
            name='TipoAcudiente',
            fields=[
                ('id_tipo_acudiente', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Acudiente',
                'verbose_name_plural': 'Tipos de Acudiente',
                'db_table': 'tipo_acudiente',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='TipoEstado',
            fields=[
                ('id_tipo_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Estado',
                'verbose_name_plural': 'Tipos de Estado',
                'db_table': 'tipo_estado',
            },
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id_tipo_sangre', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Sangre',
                'verbose_name_plural': 'Tipos de Sangre',
                'db_table': 'tipo_sangre',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('docente', 'Docente'), ('secretaria', 'Secretaría Académica'), ('coordinacion', 'Coordinación Administrativa'), ('padres', 'Padres de familia')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('numero_documento_acudiente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_codigo_municipio', models.ForeignKey(blank=True, db_column='FK_codigo_municipio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad')),
                ('fk_id_tipo_documento', models.ForeignKey(blank=True, db_column='FK_id_tipo_documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodocumento')),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'db_table': 'acudiente',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('fk_id_año_electivo', models.ForeignKey(db_column='FK_id_año_electivo', on_delete=django.db.models.deletion.CASCADE, to='core.ano_electivo')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='fk_codigo_departamento',
            field=models.ForeignKey(db_column='FK_Departamento', on_delete=django.db.models.deletion.CASCADE, to='core.departamento'),
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('numero_documento_estudiante', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('institucion_procedencia', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_codigo_municipio', models.ForeignKey(blank=True, db_column='FK_codigo_municipio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad')),
                ('fk_id_tipo_alergia', models.ForeignKey(blank=True, db_column='FK_id_tipo_alergia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alergia')),
                ('fk_id_tipo_discapacidad', models.ForeignKey(blank=True, db_column='FK_id_tipo_discapacidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discapacidad')),
                ('fk_id_genero', models.ForeignKey(blank=True, db_column='FK_id_genero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.genero')),
                ('fk_id_tipo_sisben', models.ForeignKey(blank=True, db_column='FK_id_tipo_sisben', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sisben')),
                ('fk_id_tipo_documento', models.ForeignKey(blank=True, db_column='FK_id_tipo_documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodocumento')),
                ('fk_tipo_estado', models.ForeignKey(blank=True, db_column='FK_tipo_estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoestado')),
                ('fk_id_tipo_sangre', models.ForeignKey(blank=True, db_column='FK_id_tipo_sangre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tiposangre')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes_cursos',
            fields=[
                ('id_estudiantes_cursos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True, null=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='core.cursos')),
                ('numero_documento_estudiante', models.ForeignKey(db_column='numero_documento_estudiante', on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
            ],
            options={
                'db_table': 'estudiantes_cursos',
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_ponderado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(default='Activo', max_length=50)),
                ('fk_Id_area_conocimiento', models.ForeignKey(db_column='FK_Id_area_conocimiento', on_delete=django.db.models.deletion.CASCADE, to='core.area_conocimiento')),
            ],
            options={
                'db_table': 'materias',
            },
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id_procedencia', models.IntegerField(primary_key=True, serialize=False)),
                ('institucion_procedencia', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_codigo_municipio', models.ForeignKey(blank=True, db_column='FK_codigo_municipio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad')),
            ],
            options={
                'verbose_name': 'Procedencia',
                'verbose_name_plural': 'Procedencias',
                'db_table': 'procedencia',
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('numero_documento_profesor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('fk_codigo_municipio', models.ForeignKey(blank=True, db_column='FK_codigo_municipio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad')),
                ('fk_id_tipo_documento', models.ForeignKey(blank=True, db_column='FK_id_tipo_documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodocumento')),
                ('fk_id_estado', models.ForeignKey(blank=True, db_column='FK_id_estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoestado')),
                ('fk_id_tipo_sangre', models.ForeignKey(blank=True, db_column='FK_id_tipo_sangre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tiposangre')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='MateriasAsignadas',
            fields=[
                ('id_materia_profesores', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_año_electivo', models.ForeignKey(db_column='id_año_electivo', on_delete=django.db.models.deletion.CASCADE, to='core.ano_electivo')),
                ('fk_id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='core.cursos')),
                ('fk_id_materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.CASCADE, to='core.materias')),
                ('fk_usuario_creacion', models.ForeignKey(db_column='usuario_creacion', on_delete=django.db.models.deletion.CASCADE, related_name='materias_creadas', to=settings.AUTH_USER_MODEL)),
                ('fk_numero_documento_profesor', models.ForeignKey(db_column='numero_documento_profesor', on_delete=django.db.models.deletion.CASCADE, to='core.profesores')),
            ],
            options={
                'db_table': 'materia_profesores',
            },
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_actividades', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fk_id_materia_profesores', models.ForeignKey(blank=True, db_column='FK_id_materia_profesores', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.materiasasignadas')),
                ('fk_id_periodo_academico', models.ForeignKey(db_column='FK_id_periodo_academico', on_delete=django.db.models.deletion.CASCADE, to='core.periodo')),
                ('fk_id_tipo_actividad', models.ForeignKey(db_column='FK_id_tipo_actividad', on_delete=django.db.models.deletion.CASCADE, to='core.tipoactividad')),
            ],
            options={
                'verbose_name': 'Actividades',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='EstudianteNotas',
            fields=[
                ('id_estudiante_notas', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fk_id_actividad', models.ForeignKey(db_column='fk_id_actividad', on_delete=django.db.models.deletion.CASCADE, to='core.actividades')),
                ('fk_numero_documento_estudiante', models.ForeignKey(db_column='fk_numero_documento_estudiante', on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
            ],
            options={
                'db_table': 'estudiante_notas',
                'unique_together': {('fk_numero_documento_estudiante', 'fk_id_actividad')},
            },
        ),
        migrations.CreateModel(
            name='EstudiantesAcudientes',
            fields=[
                ('id_estudiantes_acudientes', models.AutoField(primary_key=True, serialize=False)),
                ('fk_numero_documento_acudiente', models.ForeignKey(db_column='FK_numero_documento_acudiente', on_delete=django.db.models.deletion.CASCADE, to='core.acudiente')),
                ('fk_numero_documento_estudiante', models.ForeignKey(db_column='FK_numero_documento_estudiante', on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
                ('fk_id_tipo_acudiente', models.ForeignKey(blank=True, db_column='FK_id_tipo_acudiente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoacudiente')),
            ],
            options={
                'verbose_name': 'Estudiante-Acudiente',
                'verbose_name_plural': 'Estudiantes-Acudientes',
                'db_table': 'estudiantes_acudientes',
                'unique_together': {('fk_numero_documento_estudiante', 'fk_numero_documento_acudiente')},
            },
        ),
    ]
