# Generated by Django 5.2.4 on 2025-10-02 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id_tipo_alergia', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Alergia',
                'verbose_name_plural': 'Tipos de Alergia',
                'db_table': 'alergia',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id_tipo_discapacidad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Discapacidad',
                'verbose_name_plural': 'Tipos de Discapacidad',
                'db_table': 'discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='Sisben',
            fields=[
                ('id_tipo_sisben', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Sisben',
                'verbose_name_plural': 'Tipos Sisben',
                'db_table': 'sisben',
            },
        ),
        migrations.CreateModel(
            name='TipoAcudiente',
            fields=[
                ('id_tipo_acudiente', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Acudiente',
                'verbose_name_plural': 'Tipos de Acudiente',
                'db_table': 'tipo_acudiente',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='TipoEstado',
            fields=[
                ('id_tipo_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Estado',
                'verbose_name_plural': 'Tipos de Estado',
                'db_table': 'tipo_estado',
            },
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id_tipo_sangre', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Sangre',
                'verbose_name_plural': 'Tipos de Sangre',
                'db_table': 'tipo_sangre',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('numero_documento_acudiente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_codigo_municipio', models.ForeignKey(blank=True, db_column='FK_codigo_municipio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad')),
                ('fk_id_tipo_documento', models.ForeignKey(blank=True, db_column='FK_id_tipo_documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodocumento')),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'db_table': 'acudiente',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='fk_codigo_departamento',
            field=models.ForeignKey(db_column='FK_codigo_departamento', on_delete=django.db.models.deletion.CASCADE, to='core.departamento'),
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id_procedencia', models.IntegerField(primary_key=True, serialize=False)),
                ('institucion_procedencia', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_codigo_municipio', models.ForeignKey(blank=True, db_column='FK_codigo_municipio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad')),
            ],
            options={
                'verbose_name': 'Procedencia',
                'verbose_name_plural': 'Procedencias',
                'db_table': 'procedencia',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('numero_documento_estudiante', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_codigo_municipio', models.ForeignKey(blank=True, db_column='FK_codigo_municipio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad')),
                ('fk_id_tipo_alergia', models.ForeignKey(blank=True, db_column='FK_id_tipo_alergia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alergia')),
                ('fk_id_tipo_discapacidad', models.ForeignKey(blank=True, db_column='FK_id_tipo_discapacidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discapacidad')),
                ('fk_id_genero', models.ForeignKey(blank=True, db_column='FK_id_genero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.genero')),
                ('fk_id_procedencia', models.ForeignKey(blank=True, db_column='FK_id_procedencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.procedencia')),
                ('fk_id_tipo_sisben', models.ForeignKey(blank=True, db_column='FK_id_tipo_sisben', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sisben')),
                ('fk_id_tipo_documento', models.ForeignKey(blank=True, db_column='FK_id_tipo_documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodocumento')),
                ('fk_tipo_estado', models.ForeignKey(blank=True, db_column='FK_tipo_estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoestado')),
                ('fk_id_tipo_sangre', models.ForeignKey(blank=True, db_column='FK_id_tipo_sangre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tiposangre')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('numero_documento_profesor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('fk_codigo_municipio', models.ForeignKey(blank=True, db_column='FK_codigo_municipio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad')),
                ('fk_id_tipo_documento', models.ForeignKey(blank=True, db_column='FK_id_tipo_documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodocumento')),
                ('fk_id_estado', models.ForeignKey(blank=True, db_column='FK_id_estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoestado')),
                ('fk_id_tipo_sangre', models.ForeignKey(blank=True, db_column='FK_id_tipo_sangre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tiposangre')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='EstudiantesAcudientes',
            fields=[
                ('id_estudiantes_acudientes', models.AutoField(primary_key=True, serialize=False)),
                ('fk_numero_documento_acudiente', models.ForeignKey(db_column='FK_numero_documento_acudiente', on_delete=django.db.models.deletion.CASCADE, to='core.acudiente')),
                ('fk_numero_documento_estudiante', models.ForeignKey(db_column='FK_numero_documento_estudiante', on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
                ('fk_id_tipo_acudiente', models.ForeignKey(blank=True, db_column='FK_id_tipo_acudiente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoacudiente')),
            ],
            options={
                'verbose_name': 'Estudiante-Acudiente',
                'verbose_name_plural': 'Estudiantes-Acudientes',
                'db_table': 'estudiantes_acudientes',
                'unique_together': {('fk_numero_documento_estudiante', 'fk_numero_documento_acudiente')},
            },
        ),
    ]
