# Generated by Django 5.2.4 on 2026-04-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='fk_id_materia_profesores',
        ),
        migrations.RemoveField(
            model_name='actividades',
            name='fk_id_periodo_academico',
        ),
        migrations.AlterField(
            model_name='actividades',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RA',
            fields=[
                ('id_ra', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numero_ra', models.IntegerField()),
                ('fk_id_materia_profesores', models.ForeignKey(blank=True, db_column='FK_id_materia_profesores', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.materiasasignadas')),
                ('fk_id_periodo_academico', models.ForeignKey(db_column='FK_id_periodo_academico', on_delete=django.db.models.deletion.CASCADE, to='core.periodo')),
            ],
            options={
                'verbose_name': 'resultados_aprendizaje',
                'verbose_name_plural': 'resultados_aprendizaje',
                'db_table': 'resultados_aprendizaje',
            },
        ),
        migrations.AddField(
            model_name='actividades',
            name='fk_id_ra',
            field=models.ForeignKey(blank=True, db_column='FK_id_ra', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ra'),
        ),
    ]
