# Generated by Django 5.2.4 on 2026-04-25 19:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_actividades_fk_id_materia_profesores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2026, 4, 25)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividades',
            name='fk_id_ra',
            field=models.ForeignKey(db_column='FK_id_ra', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ano_electivo',
            name='id_año_electivo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='area_conocimiento',
            name='id_area_conocimiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='NotaHistorial',
            fields=[
                ('id_nota_historial', models.AutoField(primary_key=True, serialize=False)),
                ('nota_anterior', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nota_nueva', models.DecimalField(decimal_places=2, max_digits=3)),
                ('motivo_cambio', models.CharField(max_length=200)),
                ('fk_nota_estudiante', models.ForeignKey(db_column='fk_nota_estudiante', on_delete=django.db.models.deletion.CASCADE, to='core.estudiantenotas')),
            ],
            options={
                'verbose_name': 'Notas_Historial',
                'verbose_name_plural': 'notashistorial',
                'db_table': 'notas_historial',
            },
        ),
    ]
