# Generated by Django 5.2.4 on 2025-10-02 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alergia_ciudad_departamento_discapacidad_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='fk_codigo_departamento',
            field=models.ForeignKey(db_column='FK_Departamento', on_delete=django.db.models.deletion.CASCADE, to='core.departamento'),
        ),
    ]
