# Generated by Django 5.2.4 on 2025-11-12 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ciudad_fk_codigo_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ano_electivo',
            fields=[
                ('id_año_electivo', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ano_electivo',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id_tipo_actividad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'db_table': 'tipo_actividad',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_actividades', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fk_id_materia_profesores', models.ForeignKey(blank=True, db_column='FK_id_materia_profesores', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoacudiente')),
                ('fk_id_periodo_academico', models.ForeignKey(db_column='FK_id_periodo_academico', on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
                ('fk_id_tipo_actividad', models.ForeignKey(db_column='FK_id_tipo_actividad', on_delete=django.db.models.deletion.CASCADE, to='core.acudiente')),
            ],
            options={
                'verbose_name': 'Actividades',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('fk_id_año_electivo', models.ForeignKey(db_column='FK_id_año_electivo', on_delete=django.db.models.deletion.CASCADE, to='core.ano_electivo')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
    ]
