# Generated by Django 5.2.4 on 2026-04-25 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ra_nombre_ra_alter_actividades_fecha_inicio_and_more'),
    ]

    operations = [
    ]
