# Generated by Django 5.2.4 on 2025-11-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ano_electivo_tipoactividad_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_conocimiento',
            fields=[
                ('id_area_conocimiento', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'area_conocimiento',
            },
        ),
    ]
