# Generated by Django 5.2.4 on 2026-05-12 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notahistorial_fecha_cambio_ra_nombre_ra'),
    ]

    operations = [
        migrations.AddField(
            model_name='notahistorial',
            name='fecha_cambio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ra',
            name='nombre_ra',
            field=models.CharField(default='Sin Nombre', max_length=50),
        ),
        migrations.CreateModel(
            name='Definitivas',
            fields=[
                ('id_definitiva', models.AutoField(primary_key=True, serialize=False)),
                ('valor_definitiva', models.DecimalField(decimal_places=2, max_digits=3)),
                ('estado', models.CharField(max_length=50)),
                ('fk_id_materia', models.ForeignKey(db_column='fk_id_materia', on_delete=django.db.models.deletion.CASCADE, to='core.materias')),
                ('fk_numero_documento_estudiante', models.ForeignKey(db_column='fk_numero_documento_estudiante', on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
            ],
        ),
    ]
