# Generated by Django 5.2.4 on 2025-11-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_area_conocimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_ponderado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fk_Id_area_conocimiento', models.ForeignKey(db_column='FK_Id_area_conocimiento', on_delete=django.db.models.deletion.CASCADE, to='core.area_conocimiento')),
            ],
            options={
                'db_table': 'materias',
            },
        ),
    ]
