# Generated by Django 5.2.4 on 2026-05-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notahistorial_fecha_cambio_ra_nombre_ra_definitivas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='definitivas',
            table='definitiva',
        ),
    ]
