# Generated by Django 5.2.4 on 2025-11-14 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='estado',
            field=models.CharField(default='Activo', max_length=50),
        ),
        migrations.CreateModel(
            name='MateriasAsignadas',
            fields=[
                ('id_materia_profesores', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_año_electivo', models.ForeignKey(db_column='id_año_electivo', on_delete=django.db.models.deletion.CASCADE, to='core.ano_electivo')),
                ('fk_id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='core.cursos')),
                ('fk_id_materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.CASCADE, to='core.materias')),
                ('fk_numero_documento_profesor', models.ForeignKey(db_column='numero_documento_profesor', on_delete=django.db.models.deletion.CASCADE, to='core.profesores')),
                ('fk_usuario_creacion', models.ForeignKey(db_column='usuario_creacion', on_delete=django.db.models.deletion.CASCADE, related_name='materias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'materia_profesores',
            },
        ),
    ]
