# Generated by Django 5.2.4 on 2026-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_definitivas_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes_cursos',
            name='estado',
            field=models.CharField(default='activo', max_length=50),
        ),
    ]
