# Generated by Django 5.2.4 on 2025-12-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_materias_estado_materiasasignadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'periodo',
            },
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='fk_id_procedencia',
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='institucion_procedencia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='fk_id_materia_profesores',
            field=models.ForeignKey(blank=True, db_column='FK_id_materia_profesores', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.materiasasignadas'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='fk_id_tipo_actividad',
            field=models.ForeignKey(db_column='FK_id_tipo_actividad', on_delete=django.db.models.deletion.CASCADE, to='core.tipoactividad'),
        ),
        migrations.CreateModel(
            name='Estudiantes_cursos',
            fields=[
                ('id_estudiantes_cursos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True, null=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='core.cursos')),
                ('numero_documento_estudiante', models.ForeignKey(db_column='numero_documento_estudiante', on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
            ],
            options={
                'db_table': 'estudiantes_cursos',
            },
        ),
        migrations.AlterField(
            model_name='actividades',
            name='fk_id_periodo_academico',
            field=models.ForeignKey(db_column='FK_id_periodo_academico', on_delete=django.db.models.deletion.CASCADE, to='core.periodo'),
        ),
        migrations.CreateModel(
            name='EstudianteNotas',
            fields=[
                ('id_estudiante_notas', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fk_id_actividad', models.ForeignKey(db_column='fk_id_actividad', on_delete=django.db.models.deletion.CASCADE, to='core.actividades')),
                ('fk_numero_documento_estudiante', models.ForeignKey(db_column='fk_numero_documento_estudiante', on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
            ],
            options={
                'db_table': 'estudiante_notas',
                'unique_together': {('fk_numero_documento_estudiante', 'fk_id_actividad')},
            },
        ),
    ]
