# Generated by Django 5.2.4 on 2026-05-13 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_estudiantes_cursos_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definitivas',
            name='fk_numero_documento_estudiante',
        ),
        migrations.AddField(
            model_name='definitivas',
            name='fk_id_estudiantes_cursos',
            field=models.ForeignKey(db_column='fk_numero_documento_estudiante', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes_cursos'),
        ),
    ]
