# Generated by Django 5.2.4 on 2026-05-13 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_definitivas_fk_numero_documento_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='definitivas',
            name='fk_id_periodo',
            field=models.ForeignKey(db_column='fk_id_periodo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.periodo'),
        ),
        migrations.AlterField(
            model_name='definitivas',
            name='fk_id_estudiantes_cursos',
            field=models.ForeignKey(db_column='fk_id_estudiantes_cursos', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes_cursos'),
        ),
    ]
